### ISSUE TITLE
missing file ?

### ISSUE THREAD

**Issue by garfield38** [fay2003hiend/avrdude-gui#1]
Hello,

programmer list and Device list are empty.

I think this is because Qavrdude.ini file is missing.

Thanks
Stephane

**Comment by fay2003hiend** [comment]
Hi Garfield

Thanks for your feedback! you will need to add bin/avrdude.exe bin/avrdude.conf files before compile, then  it will extract at runtime and get the list from avrdude program

**Comment by fay2003hiend** [comment]
have updated the code to include avrdude.exe version 6.3

**Comment by garfield38** [comment]
Thanks, I have understood that later after my message. I'm on Mac, so I have added the binary avrdude file but I still have an issue, waitForStarted return false and I'm not expert on Qt to understand why.
